//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halldata.EMS.CustomAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=DB2OLEDB;Data Source=DBS-HDS-01;Password=pr050018;User ID=SQLSPROD;Initi" +
            "al Catalog=S10CBA7R;Network Address=AS400.HALLDATA.COM;Package Collection=PRODCO" +
            "LL;Default Schema=PRODCOLL;Default Qualifier=PRODCOLL;DBMS Platform=DB2/AS400")]
        public string db2connectionstring {
            get {
                return ((string)(this["db2connectionstring"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=ods04.prd.halldata.local;uid=dragonapi;password=TFufL-2xfCPD68j=;database=" +
            "dragon;Allow Zero Datetime=true;")]
        public string mysqlconnectionstring {
            get {
                return ((string)(this["mysqlconnectionstring"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AvvD5Tt6Uy78jH1277Df3F")]
        public string API_Key {
            get {
                return ((string)(this["API_Key"]));
            }
        }
    }
}
